/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ColoresResistencias;

import Interfaces.Menu;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author David Peñavasquez Va
 */
public class Cuatrobandas extends javax.swing.JFrame {

    /**
     * Creates new form Cuatrobandas
     */
    public Cuatrobandas() {
        initComponents();
        this.setLocationRelativeTo(null);
           BTNC3.setBackground(Color.black);
                    BTNC4.setBackground(new Color(153,51,0));
                     BTNC5.setBackground(Color.red);
                     BTNC6.setBackground(Color.orange);
                     BTNC7.setBackground(Color.yellow);
                     BTNC11.setBackground(Color.green);
                     BTNC9.setBackground(new Color(102,0,102));
                     BTNC10.setBackground(new Color(102,102,102));
                     BTNC8.setBackground(Color.blue);
                     BTNC12.setBackground(Color.white);
                   
          
               C15.setBackground(Color.black);
                    C16.setBackground(new Color(153,51,0));
                     C17.setBackground(Color.red);
                     C18.setBackground(Color.orange);
                     C19.setBackground(Color.yellow);
                     C20.setBackground(Color.green);
                     C21.setBackground(Color.blue);
                     C22.setBackground(new Color(102,0,102));
                     C23.setBackground(new Color(102,102,102));
                     C24.setBackground(Color.white);
                    
       
               C27.setBackground(Color.black);
                    C28.setBackground(new Color(153,51,0));
                     C29.setBackground(Color.red);
                     C30.setBackground(Color.orange);
                     C31.setBackground(Color.yellow);
                     C32.setBackground(Color.green);
                     C33.setBackground(Color.blue);
                     C34.setBackground(new Color(102,0,102));
                     C35.setBackground(new Color(102,102,102));
                     C36.setBackground(Color.white);
                     
                     
               C37.setBackground(Color.black);
                    C38.setBackground(new Color(153,51,0));
                     C39.setBackground(Color.red);
                     C40.setBackground(Color.orange);
                     C41.setBackground(Color.yellow);
                     C42.setBackground(Color.green);
                     C43.setBackground(Color.blue);
                     C44.setBackground(new Color(102,0,102));
                     C45.setBackground(new Color(102,102,102));
                     C46.setBackground(Color.white);
                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BTNC3 = new javax.swing.JButton();
        BTNC4 = new javax.swing.JButton();
        BTNC5 = new javax.swing.JButton();
        BTNC6 = new javax.swing.JButton();
        BTNC7 = new javax.swing.JButton();
        BTNC8 = new javax.swing.JButton();
        BTNC9 = new javax.swing.JButton();
        BTNC10 = new javax.swing.JButton();
        BTNC11 = new javax.swing.JButton();
        BTNC12 = new javax.swing.JButton();
        C15 = new javax.swing.JButton();
        C16 = new javax.swing.JButton();
        C17 = new javax.swing.JButton();
        C18 = new javax.swing.JButton();
        C19 = new javax.swing.JButton();
        C20 = new javax.swing.JButton();
        C21 = new javax.swing.JButton();
        C22 = new javax.swing.JButton();
        C23 = new javax.swing.JButton();
        C24 = new javax.swing.JButton();
        C27 = new javax.swing.JButton();
        C28 = new javax.swing.JButton();
        C29 = new javax.swing.JButton();
        C30 = new javax.swing.JButton();
        C31 = new javax.swing.JButton();
        C32 = new javax.swing.JButton();
        C33 = new javax.swing.JButton();
        C34 = new javax.swing.JButton();
        C35 = new javax.swing.JButton();
        C36 = new javax.swing.JButton();
        C37 = new javax.swing.JButton();
        C38 = new javax.swing.JButton();
        C39 = new javax.swing.JButton();
        C40 = new javax.swing.JButton();
        C41 = new javax.swing.JButton();
        C42 = new javax.swing.JButton();
        C43 = new javax.swing.JButton();
        C44 = new javax.swing.JButton();
        C45 = new javax.swing.JButton();
        C46 = new javax.swing.JButton();
        J1 = new javax.swing.JTextField();
        J2 = new javax.swing.JTextField();
        J3 = new javax.swing.JTextField();
        J6 = new javax.swing.JTextField();
        J4 = new javax.swing.JTextField();
        J5 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        RES1 = new javax.swing.JTextField();
        RES2 = new javax.swing.JTextField();
        RES3 = new javax.swing.JTextField();
        RES6 = new javax.swing.JTextField();
        CBMULTIPLICADOR = new javax.swing.JComboBox<>();
        CBTOLERANCIA = new javax.swing.JComboBox<>();
        RES4 = new javax.swing.JTextField();
        RES5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        TOLERANCIA = new javax.swing.JLabel();
        BAND = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        SALIR1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AREA = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Negro");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Marron");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Rojo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Naranja");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Amarillo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Verde");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Azul");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Violeta");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Gris");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Blanco");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        BTNC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC3ActionPerformed(evt);
            }
        });
        getContentPane().add(BTNC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 50, 20));

        BTNC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC4ActionPerformed(evt);
            }
        });
        getContentPane().add(BTNC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 50, 20));

        BTNC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC5ActionPerformed(evt);
            }
        });
        getContentPane().add(BTNC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 50, 20));

        BTNC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC6ActionPerformed(evt);
            }
        });
        getContentPane().add(BTNC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 50, 20));

        BTNC7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC7ActionPerformed(evt);
            }
        });
        getContentPane().add(BTNC7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 50, 20));

        BTNC8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC8ActionPerformed(evt);
            }
        });
        getContentPane().add(BTNC8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 50, 20));

        BTNC9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC9ActionPerformed(evt);
            }
        });
        getContentPane().add(BTNC9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 50, 20));

        BTNC10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC10ActionPerformed(evt);
            }
        });
        getContentPane().add(BTNC10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 50, 20));

        BTNC11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC11ActionPerformed(evt);
            }
        });
        getContentPane().add(BTNC11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 50, 20));

        BTNC12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC12ActionPerformed(evt);
            }
        });
        getContentPane().add(BTNC12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 50, 20));

        C15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C15ActionPerformed(evt);
            }
        });
        getContentPane().add(C15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 50, 20));

        C16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C16ActionPerformed(evt);
            }
        });
        getContentPane().add(C16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 50, 20));

        C17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C17ActionPerformed(evt);
            }
        });
        getContentPane().add(C17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 50, 20));

        C18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C18ActionPerformed(evt);
            }
        });
        getContentPane().add(C18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 50, 20));

        C19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C19ActionPerformed(evt);
            }
        });
        getContentPane().add(C19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 50, 20));

        C20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C20ActionPerformed(evt);
            }
        });
        getContentPane().add(C20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 50, 20));

        C21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C21ActionPerformed(evt);
            }
        });
        getContentPane().add(C21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 50, 20));

        C22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C22ActionPerformed(evt);
            }
        });
        getContentPane().add(C22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 50, 20));

        C23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C23ActionPerformed(evt);
            }
        });
        getContentPane().add(C23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 50, 20));

        C24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C24ActionPerformed(evt);
            }
        });
        getContentPane().add(C24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 50, 20));

        C27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C27ActionPerformed(evt);
            }
        });
        getContentPane().add(C27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 50, 20));

        C28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C28ActionPerformed(evt);
            }
        });
        getContentPane().add(C28, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 50, 20));

        C29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C29ActionPerformed(evt);
            }
        });
        getContentPane().add(C29, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 50, 20));

        C30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C30ActionPerformed(evt);
            }
        });
        getContentPane().add(C30, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 50, 20));

        C31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C31ActionPerformed(evt);
            }
        });
        getContentPane().add(C31, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 50, 20));

        C32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C32ActionPerformed(evt);
            }
        });
        getContentPane().add(C32, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 50, 20));

        C33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C33ActionPerformed(evt);
            }
        });
        getContentPane().add(C33, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 50, 20));

        C34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C34ActionPerformed(evt);
            }
        });
        getContentPane().add(C34, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 50, 20));

        C35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C35ActionPerformed(evt);
            }
        });
        getContentPane().add(C35, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 50, 20));

        C36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C36ActionPerformed(evt);
            }
        });
        getContentPane().add(C36, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 50, 20));

        C37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C37ActionPerformed(evt);
            }
        });
        getContentPane().add(C37, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 50, 20));

        C38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C38ActionPerformed(evt);
            }
        });
        getContentPane().add(C38, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 50, 20));

        C39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C39ActionPerformed(evt);
            }
        });
        getContentPane().add(C39, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 50, 20));

        C40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C40ActionPerformed(evt);
            }
        });
        getContentPane().add(C40, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 50, 20));

        C41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C41ActionPerformed(evt);
            }
        });
        getContentPane().add(C41, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 50, 20));

        C42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C42ActionPerformed(evt);
            }
        });
        getContentPane().add(C42, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 50, 20));

        C43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C43ActionPerformed(evt);
            }
        });
        getContentPane().add(C43, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 50, 20));

        C44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C44ActionPerformed(evt);
            }
        });
        getContentPane().add(C44, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 50, 20));

        C45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C45ActionPerformed(evt);
            }
        });
        getContentPane().add(C45, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 50, 20));

        C46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C46ActionPerformed(evt);
            }
        });
        getContentPane().add(C46, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 50, 20));

        J1.setEditable(false);
        J1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J1ActionPerformed(evt);
            }
        });
        getContentPane().add(J1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 20, 80));

        J2.setEditable(false);
        getContentPane().add(J2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 20, 80));

        J3.setEditable(false);
        getContentPane().add(J3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 20, 80));

        J6.setEditable(false);
        J6.setHighlighter(null);
        J6.setRequestFocusEnabled(false);
        J6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J6ActionPerformed(evt);
            }
        });
        getContentPane().add(J6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 20, 80));

        J4.setEditable(false);
        J4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J4ActionPerformed(evt);
            }
        });
        getContentPane().add(J4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 20, 80));

        J5.setEditable(false);
        getContentPane().add(J5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 20, 80));
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        RES1.setEditable(false);
        RES1.setBackground(new java.awt.Color(255, 255, 255));
        RES1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RES1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RES1ActionPerformed(evt);
            }
        });
        getContentPane().add(RES1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 120, 30));

        RES2.setEditable(false);
        RES2.setBackground(new java.awt.Color(255, 255, 255));
        RES2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(RES2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 110, 30));

        RES3.setEditable(false);
        RES3.setBackground(new java.awt.Color(255, 255, 255));
        RES3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RES3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RES3ActionPerformed(evt);
            }
        });
        getContentPane().add(RES3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 110, 30));

        RES6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(RES6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 110, 30));

        CBMULTIPLICADOR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CBMULTIPLICADOR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MULTIPLICADOR", "PLATA", "ORO", "NEGRO", "MARRON", "ROJO", "NARANJA", "AMARILLO", "VERDE", "AZUL", " " }));
        CBMULTIPLICADOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMULTIPLICADORActionPerformed(evt);
            }
        });
        getContentPane().add(CBMULTIPLICADOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 90, 200));

        CBTOLERANCIA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CBTOLERANCIA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TOLERANCIA", "PLATA", "ORO", "MARRON", "ROJO", "NARANJA", "AMARILLO", "VERDE", "SIN COLOR", " " }));
        CBTOLERANCIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTOLERANCIAActionPerformed(evt);
            }
        });
        getContentPane().add(CBTOLERANCIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 100, 200));

        RES4.setEditable(false);
        RES4.setBackground(new java.awt.Color(255, 255, 255));
        RES4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(RES4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, 100, 30));

        RES5.setEditable(false);
        RES5.setBackground(new java.awt.Color(255, 255, 255));
        RES5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(RES5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 480, 100, 30));

        jButton5.setBackground(new java.awt.Color(0, 153, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("REINICIAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 130, 30));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 153, 153));
        jLabel42.setText("CODIGO DE COLORES DE RESISTENCIAS");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel44.setText("BANDA 1");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel46.setText("BANDA 2");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel48.setText("BANDA 4");
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, 30));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel50.setText("BANDA 3");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, 20));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel52.setText("MULTIPLICADOR");
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 170, 30));

        TOLERANCIA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TOLERANCIA.setText("TOLERANCIA");
        getContentPane().add(TOLERANCIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, -1, 30));

        BAND.setBackground(new java.awt.Color(0, 153, 153));
        BAND.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BAND.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÚMERO DE BANDAS:", "DOS BANDAS", "TRES BANDAS" }));
        BAND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BANDActionPerformed(evt);
            }
        });
        getContentPane().add(BAND, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 220, 30));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setText("Negro");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setText("Marron");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setText("Rojo");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setText("Naranja");
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel51.setText("Amarillo");
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel53.setText("Verde");
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel54.setText("Azul");
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel55.setText("Violeta");
        getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setText("Gris");
        getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setText("Blanco");
        getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setText("Negro");
        getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel59.setText("Marron");
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel60.setText("Rojo");
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel61.setText("Naranja");
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel62.setText("Amarillo");
        getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel63.setText("Verde");
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel64.setText("Azul");
        getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel65.setText("Violeta");
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel66.setText("Gris");
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel67.setText("Blanco");
        getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel68.setText("Violeta");
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel69.setText("Verde");
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel70.setText("Azul");
        getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel71.setText("Negro");
        getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel72.setText("Rojo");
        getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel73.setText("Amarillo");
        getContentPane().add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel74.setText("Blanco");
        getContentPane().add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, -1, -1));

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel75.setText("Marron");
        getContentPane().add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel76.setText("Naranja");
        getContentPane().add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, -1));

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel77.setText("Gris");
        getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        SALIR1.setBackground(new java.awt.Color(0, 153, 153));
        SALIR1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SALIR1.setForeground(new java.awt.Color(255, 255, 255));
        SALIR1.setText("REGRESAR");
        SALIR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIR1ActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 130, 30));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Resistor.png"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("MΩ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 550, 80, 30));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("KΩ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, 80, 30));

        AREA.setEditable(false);
        AREA.setColumns(20);
        AREA.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        AREA.setRows(5);
        jScrollPane1.setViewportView(AREA);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 360, 70));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 120, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1040, 630));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1070, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNC9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC9ActionPerformed
     J1.setBackground(Color.blue);
           int r=6;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);   // TODO add your handling code here:
    }//GEN-LAST:event_BTNC9ActionPerformed

    private void J1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J1ActionPerformed

    }//GEN-LAST:event_J1ActionPerformed

    private void J6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J6ActionPerformed

    private void J4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J4ActionPerformed

    private void RES1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RES1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RES1ActionPerformed

    private void CBMULTIPLICADORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMULTIPLICADORActionPerformed

        if(CBMULTIPLICADOR.getSelectedIndex()==1){
            CBMULTIPLICADOR.setBackground(new Color(153,153,153));
            J4.setBackground(new Color(153,153,153));
            double r= 0.01;
            String res;
            res=Double.toString(r);
            RES4.setText(res);

        }
        if(CBMULTIPLICADOR.getSelectedIndex()==2){
            CBMULTIPLICADOR.setBackground(new Color(255,204,51));
            J4.setBackground(new Color(255,204,51));
            double r= 0.1;
            String res;
            res=Double.toString(r);
            RES4.setText(res);
        }
        if(CBMULTIPLICADOR.getSelectedIndex()==3){
            CBMULTIPLICADOR.setBackground(Color.black);
            J4.setBackground(Color.black);
            double r= 1;
            String res;
            res=Double.toString(r);
            RES4.setText(res);
        }
        if(CBMULTIPLICADOR.getSelectedIndex()==4){
            CBMULTIPLICADOR.setBackground(new Color(153,51,0));
            J4.setBackground(new Color(153,51,0));
            double r= 10;
            String res;
            res=Double.toString(r);
            RES4.setText(res);
        }
        if(CBMULTIPLICADOR.getSelectedIndex()==5){
            CBMULTIPLICADOR.setBackground(Color.red);
            J4.setBackground(Color.red);
            double r= 100;
            String res;
            res=Double.toString(r);
            RES4.setText(res);
        }
        if(CBMULTIPLICADOR.getSelectedIndex()==6){
            CBMULTIPLICADOR.setBackground(Color.orange);
            J4.setBackground(Color.orange);
            double r= 1000;
            String res;
            res=Double.toString(r);
            RES4.setText(res);

        }
        if(CBMULTIPLICADOR.getSelectedIndex()==7){
            CBMULTIPLICADOR.setBackground(Color.yellow);
            J4.setBackground(Color.yellow);
            double r= 10000;
            String res;
            res=Double.toString(r);
            RES4.setText(res);
        }
        if(CBMULTIPLICADOR.getSelectedIndex()==8){
            CBMULTIPLICADOR.setBackground(Color.green);
            J4.setBackground(Color.green);
            double r= 1000000;
            String res;
            res=Double.toString(r);
            RES4.setText(res);
        }
        if(CBMULTIPLICADOR.getSelectedIndex()==9){
            CBMULTIPLICADOR.setBackground(Color.blue);
            J4.setBackground(Color.blue);
            double r= 10000000;
            String res;
            res=Double.toString(r);
            RES4.setText(res);
        }

    }//GEN-LAST:event_CBMULTIPLICADORActionPerformed

    private void CBTOLERANCIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTOLERANCIAActionPerformed
        if(CBTOLERANCIA.getSelectedIndex()==1){
            CBTOLERANCIA.setBackground(new Color(153,153,153));
            J5.setBackground(new Color(153,153,153));
            double r= 0.1;
            String res;
            res=Double.toString(r);
            RES5.setText(res);

        }
        if(CBTOLERANCIA.getSelectedIndex()==2){
            CBTOLERANCIA.setBackground(new Color(255,204,51));
            J5.setBackground(new Color(255,204,51));
            double r= 0.05;
            String res;
            res=Double.toString(r);
            RES5.setText(res);
        }
        if(CBTOLERANCIA.getSelectedIndex()==3){
            CBTOLERANCIA.setBackground(new Color(153,51,0));
            J5.setBackground(new Color(153,51,0));
            double r= 0.01;
            String res;
            res=Double.toString(r);
            RES5.setText(res);
        }
        if(CBTOLERANCIA.getSelectedIndex()==4){
            CBTOLERANCIA.setBackground(Color.red);
            J5.setBackground(Color.red);
            double r= 0.02;
            String res;
            res=Double.toString(r);
            RES5.setText(res);
        }
        if(CBTOLERANCIA.getSelectedIndex()==5){
            CBTOLERANCIA.setBackground(Color.orange);
            J5.setBackground(Color.orange);
            double r= 0.03;
            String res;
            res=Double.toString(r);
            RES5.setText(res);
        }
        if(CBTOLERANCIA.getSelectedIndex()==6){
            CBTOLERANCIA.setBackground(Color.yellow);
            J5.setBackground(Color.yellow);
            double r= 0.04;
            String res;
            res=Double.toString(r);
            RES5.setText(res);

        }
        if(CBTOLERANCIA.getSelectedIndex()==7){
            CBTOLERANCIA.setBackground(Color.green);
            J5.setBackground(Color.green);
            double r= 0.005;
            String res;
            res=Double.toString(r);
            RES5.setText(res);
        }
        if(CBTOLERANCIA.getSelectedIndex()==8){
            CBTOLERANCIA.setBackground(Color.WHITE);
            J5.setBackground(Color.WHITE);
            double r= 0.2;
            String res;
            res=Double.toString(r);
            RES5.setText(res);
        }

    }//GEN-LAST:event_CBTOLERANCIAActionPerformed

    private void BTNC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC3ActionPerformed
        J1.setBackground(Color.black);
        int r=0;
        String res;
        res=Integer.toString(r);
        
        RES1.setText(res);
    }//GEN-LAST:event_BTNC3ActionPerformed

    private void BTNC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC4ActionPerformed
  J1.setBackground(new Color(153,51,0));
        int r=1;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_BTNC4ActionPerformed

    private void BTNC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC5ActionPerformed
 J1.setBackground(Color.red);
        int r=2;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_BTNC5ActionPerformed

    private void BTNC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC6ActionPerformed
 J1.setBackground(Color.orange);
            int r=3;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_BTNC6ActionPerformed

    private void BTNC7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC7ActionPerformed
 J1.setBackground(Color.yellow);
           int r=4;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_BTNC7ActionPerformed

    private void BTNC8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC8ActionPerformed
 J1.setBackground(Color.green);
            int r=5;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_BTNC8ActionPerformed

    private void BTNC10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC10ActionPerformed
 J1.setBackground(new Color(102,0,102));
        int r=7;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_BTNC10ActionPerformed

    private void BTNC11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC11ActionPerformed
  J1.setBackground(new Color(102,102,102));
          int r=8;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_BTNC11ActionPerformed

    private void BTNC12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC12ActionPerformed
 J1.setBackground(Color.white);
            int r=9;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_BTNC12ActionPerformed

    private void C15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C15ActionPerformed
 J2.setBackground(Color.black);
           int r=0;
        String res;
        res=Integer.toString(r);
        
        RES2.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C15ActionPerformed

    private void C16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C16ActionPerformed
  J2.setBackground(new Color(153,51,0));
              int r=1;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C16ActionPerformed

    private void C17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C17ActionPerformed
           J2.setBackground(Color.red);
            int r=2;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);
    }//GEN-LAST:event_C17ActionPerformed

    private void C18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C18ActionPerformed
J2.setBackground(Color.orange);
             int r=3;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C18ActionPerformed

    private void C19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C19ActionPerformed
 J2.setBackground(Color.yellow);
            int r=4;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C19ActionPerformed

    private void C20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C20ActionPerformed
 J2.setBackground(Color.green);
           int r=5;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C20ActionPerformed

    private void C21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C21ActionPerformed
 J2.setBackground(Color.blue);
             int r=6;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C21ActionPerformed

    private void C22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C22ActionPerformed
         J2.setBackground(new Color(102,0,102));
           int r=7;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);
    }//GEN-LAST:event_C22ActionPerformed

    private void C23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C23ActionPerformed
 J2.setBackground(new Color(102,102,102));
          int r=8;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C23ActionPerformed

    private void C24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C24ActionPerformed
 J2.setBackground(Color.white);
             int r=9;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C24ActionPerformed

    private void C27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C27ActionPerformed
        J3.setBackground(Color.black);
          
           int r=0;
        String res;
        res=Integer.toString(r);
        
        RES3.setText(res);
    }//GEN-LAST:event_C27ActionPerformed

    private void C28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C28ActionPerformed
J3.setBackground(new Color(153,51,0));
                int r=1;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C28ActionPerformed

    private void C29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C29ActionPerformed
        J3.setBackground(Color.red);
             int r=2;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);
    }//GEN-LAST:event_C29ActionPerformed

    private void C30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C30ActionPerformed
J3.setBackground(Color.orange);
                int r=3;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C30ActionPerformed

    private void C31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C31ActionPerformed
J3.setBackground(Color.yellow);
               int r=4;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C31ActionPerformed

    private void C32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C32ActionPerformed
 J3.setBackground(Color.green);
                int r=5;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C32ActionPerformed

    private void C33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C33ActionPerformed
J3.setBackground(Color.blue);
             int r=6;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C33ActionPerformed

    private void C34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C34ActionPerformed
J3.setBackground(new Color(102,0,102));
            int r=7;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C34ActionPerformed

    private void C35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C35ActionPerformed
J3.setBackground(new Color(102,102,102));
         int r=8;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C35ActionPerformed

    private void C36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C36ActionPerformed
 J3.setBackground(Color.white);
             int r=9;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C36ActionPerformed

    private void C37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C37ActionPerformed
 J6.setBackground(Color.black);
          
           int r=0;
        String res;
        res=Integer.toString(r);
        
        RES6.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C37ActionPerformed

    private void C38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C38ActionPerformed
J6.setBackground(new Color(153,51,0));
                int r=1;
            String res;
        res=Integer.toString(r);
        
        RES6.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C38ActionPerformed

    private void C39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C39ActionPerformed
 J6.setBackground(Color.red);
             int r=2;
            String res;
        res=Integer.toString(r);
        
        RES6.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C39ActionPerformed

    private void C40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C40ActionPerformed
J6.setBackground(Color.orange);
                int r=3;
            String res;
        res=Integer.toString(r);
        
        RES6.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C40ActionPerformed

    private void C41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C41ActionPerformed
 J6.setBackground(Color.yellow);
               int r=4;
            String res;
        res=Integer.toString(r);
        
        RES6.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C41ActionPerformed

    private void C42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C42ActionPerformed
J6.setBackground(Color.green);
                int r=5;
            String res;
        res=Integer.toString(r);
        
        RES6.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C42ActionPerformed

    private void C43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C43ActionPerformed
  J6.setBackground(Color.blue);
             int r=6;
            String res;
        res=Integer.toString(r);
        
        RES6.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C43ActionPerformed

    private void C44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C44ActionPerformed
J6.setBackground(new Color(102,0,102));
            int r=7;
            String res;
        res=Integer.toString(r);
        
        RES6.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C44ActionPerformed

    private void C45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C45ActionPerformed
 J6.setBackground(new Color(102,102,102));
         int r=8;
            String res;
        res=Integer.toString(r);
        
        RES6.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C45ActionPerformed

    private void C46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C46ActionPerformed
J6.setBackground(Color.white);
             int r=9;
            String res;
        res=Integer.toString(r);
        
        RES6.setText(res);        // TODO add your handling code here:
    }//GEN-LAST:event_C46ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int campo1=Integer.parseInt(RES1.getText());
        int campo2=Integer.parseInt(RES2.getText());
        int campo3=Integer.parseInt(RES3.getText());
         int campo6=Integer.parseInt(RES6.getText());
        double campo4=Double.parseDouble(RES4.getText());
        double campo5=Double.parseDouble(RES5.getText());

        String campoo1=Integer.toString(campo1);
        String campoo2=Integer.toString(campo2);
        String campoo3=Integer.toString(campo3);
          String campoo6=Integer.toString(campo6);
        String campoo4=Double.toString(campo4);
        String campoo5=Double.toString(campo5);

        String conca=campoo1.concat(campoo2.concat(campoo3.concat(campoo6)));
        int result2= Integer.parseInt(conca);
        double resolv= result2*campo4;
        double resolv2= resolv*campo5;
        String nuevo=Double.toString(resolv);
        String nuevo1=Double.toString(resolv2);
        AREA.append("LA RESISTENCIA ES :");
        AREA.append(System.getProperty("line.separator"));
        AREA.append(nuevo+"  +/-  "+ nuevo1 +"‎Ω");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   int campo1=Integer.parseInt(RES1.getText());
   int campo2=Integer.parseInt(RES2.getText());
   int campo3=Integer.parseInt(RES3.getText());
   int campo6=Integer.parseInt(RES6.getText());
   double campo4=Double.parseDouble(RES4.getText());
    double campo5=Double.parseDouble(RES5.getText());
  
  
 String campoo1=Integer.toString(campo1);
 String campoo2=Integer.toString(campo2);
 String campoo3=Integer.toString(campo3);
  String campoo6=Integer.toString(campo6);
  String campoo4=Double.toString(campo4);
    String campoo5=Double.toString(campo5);
  

 
 String conca=campoo1.concat(campoo2.concat(campoo3.concat(campoo6)));
   int result2= Integer.parseInt(conca);
   double resolv= result2*campo4;
   double resolv2= resolv*campo5;
  double convertidor=resolv/1000;
  double convertidor2=resolv2/1000;
  JOptionPane.showMessageDialog(null, " LA RESPUESTA EN K‎Ω: " + convertidor+"  +/-  "+convertidor2+" K‎Ω ");    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         int campo1=Integer.parseInt(RES1.getText());
   int campo2=Integer.parseInt(RES2.getText());
   int campo3=Integer.parseInt(RES3.getText());
   int campo6=Integer.parseInt(RES6.getText());
   double campo4=Double.parseDouble(RES4.getText());
    double campo5=Double.parseDouble(RES5.getText());
  
  
 String campoo1=Integer.toString(campo1);
 String campoo2=Integer.toString(campo2);
 String campoo3=Integer.toString(campo3);
 String campoo6=Integer.toString(campo6);
  String campoo4=Double.toString(campo4);
    String campoo5=Double.toString(campo5);
  

 
 String conca=campoo1.concat(campoo2.concat(campoo3.concat(campoo6)));
   int result2= Integer.parseInt(conca);
   double resolv= result2*campo4;
   double resolv2= resolv*campo5;
  double convertidor=resolv/1000000;
  double convertidor2=resolv2/1000000;
  JOptionPane.showMessageDialog(null, " LA RESPUESTA EN MΩ: " + convertidor+"  +/-  "+convertidor2+" MΩ ");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        J1.setBackground(Color.white);
        J2.setBackground(Color.white);
        J3.setBackground(Color.white);
        J4.setBackground(Color.white);
        J5.setBackground(Color.white);
        
              J6.setBackground(Color.white);
        CBMULTIPLICADOR.setSelectedIndex(0);
        CBMULTIPLICADOR.setBackground(Color.white);
        CBTOLERANCIA.setSelectedIndex(0);
        CBTOLERANCIA.setBackground(Color.white);

        RES1.setText("");
        RES2.setText("");
        RES3.setText("");
        RES6.setText("");
        RES4.setText("");
        RES5.setText("");
        AREA.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void BANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BANDActionPerformed
        Banda2 n= new Banda2();
        probando j= new probando();
        if(BAND.getSelectedIndex()==1){
            n.setVisible(true);
            dispose();

        }
         if(BAND.getSelectedIndex()==2){
            j.setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_BANDActionPerformed

    private void RES3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RES3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RES3ActionPerformed

    private void SALIR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIR1ActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SALIR1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuatrobandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuatrobandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuatrobandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuatrobandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuatrobandas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AREA;
    private javax.swing.JComboBox<String> BAND;
    private javax.swing.JButton BTNC10;
    private javax.swing.JButton BTNC11;
    private javax.swing.JButton BTNC12;
    private javax.swing.JButton BTNC3;
    private javax.swing.JButton BTNC4;
    private javax.swing.JButton BTNC5;
    private javax.swing.JButton BTNC6;
    private javax.swing.JButton BTNC7;
    private javax.swing.JButton BTNC8;
    private javax.swing.JButton BTNC9;
    private javax.swing.JButton C15;
    private javax.swing.JButton C16;
    private javax.swing.JButton C17;
    private javax.swing.JButton C18;
    private javax.swing.JButton C19;
    private javax.swing.JButton C20;
    private javax.swing.JButton C21;
    private javax.swing.JButton C22;
    private javax.swing.JButton C23;
    private javax.swing.JButton C24;
    private javax.swing.JButton C27;
    private javax.swing.JButton C28;
    private javax.swing.JButton C29;
    private javax.swing.JButton C30;
    private javax.swing.JButton C31;
    private javax.swing.JButton C32;
    private javax.swing.JButton C33;
    private javax.swing.JButton C34;
    private javax.swing.JButton C35;
    private javax.swing.JButton C36;
    private javax.swing.JButton C37;
    private javax.swing.JButton C38;
    private javax.swing.JButton C39;
    private javax.swing.JButton C40;
    private javax.swing.JButton C41;
    private javax.swing.JButton C42;
    private javax.swing.JButton C43;
    private javax.swing.JButton C44;
    private javax.swing.JButton C45;
    private javax.swing.JButton C46;
    private javax.swing.JComboBox<String> CBMULTIPLICADOR;
    private javax.swing.JComboBox<String> CBTOLERANCIA;
    private javax.swing.JTextField J1;
    private javax.swing.JTextField J2;
    private javax.swing.JTextField J3;
    private javax.swing.JTextField J4;
    private javax.swing.JTextField J5;
    private javax.swing.JTextField J6;
    private javax.swing.JTextField RES1;
    private javax.swing.JTextField RES2;
    private javax.swing.JTextField RES3;
    private javax.swing.JTextField RES4;
    private javax.swing.JTextField RES5;
    private javax.swing.JTextField RES6;
    private javax.swing.JButton SALIR1;
    private javax.swing.JLabel TOLERANCIA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
