/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ColoresResistencias;

import javax.swing.JOptionPane;

/**
 *
 * @author David Peñavasquez Va
 */
public class Distancia extends javax.swing.JFrame {

    /**
     * Creates new form Distancia
     */
    public Distancia() {
        initComponents();
           CALCULARE.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNCALCULAR = new javax.swing.JButton();
        CALCULARE = new javax.swing.JButton();
        BTNLIMPIAR = new javax.swing.JButton();
        BTNSALIR = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        TXTDIST = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        txtelevado3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtelevado2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtelevado1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcarga2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RBELECTRONES = new javax.swing.JRadioButton();
        txtcarga1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FISICA ll");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNCALCULAR.setBackground(new java.awt.Color(0, 0, 255));
        BTNCALCULAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNCALCULAR.setForeground(new java.awt.Color(255, 255, 255));
        BTNCALCULAR.setText("CALCULAR");
        BTNCALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCALCULARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNCALCULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 110, 50));

        CALCULARE.setBackground(new java.awt.Color(0, 0, 255));
        CALCULARE.setForeground(new java.awt.Color(255, 255, 255));
        CALCULARE.setText("CACULAR(e)");
        CALCULARE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULAREActionPerformed(evt);
            }
        });
        getContentPane().add(CALCULARE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 110, 50));

        BTNLIMPIAR.setBackground(new java.awt.Color(255, 0, 0));
        BTNLIMPIAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNLIMPIAR.setForeground(new java.awt.Color(255, 255, 255));
        BTNLIMPIAR.setText("LIMPIAR CAMPOS");
        BTNLIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLIMPIARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNLIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, 40));

        BTNSALIR.setBackground(new java.awt.Color(255, 0, 0));
        BTNSALIR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNSALIR.setForeground(new java.awt.Color(255, 255, 255));
        BTNSALIR.setText("SALIR");
        BTNSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(BTNSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 120, 40));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 204, 0))); // NOI18N

        TXTDIST.setEditable(false);
        jLayeredPane1.add(TXTDIST);
        TXTDIST.setBounds(140, 40, 158, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 153));
        jLabel11.setText("metros");
        jLayeredPane1.add(jLabel11);
        jLabel11.setBounds(330, 50, 41, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 153));
        jLabel10.setText("LA DISTANCIA ES :");
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(20, 50, 101, 14);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 400, 110));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESAR DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 204, 0))); // NOI18N
        jLayeredPane2.add(txtelevado3);
        txtelevado3.setBounds(280, 140, 129, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("N");
        jLayeredPane2.add(jLabel9);
        jLabel9.setBounds(420, 150, 7, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 0));
        jLabel8.setText("x10^");
        jLayeredPane2.add(jLabel8);
        jLabel8.setBounds(240, 150, 30, 14);
        jLayeredPane2.add(txtelevado2);
        txtelevado2.setBounds(280, 100, 129, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("C");
        jLayeredPane2.add(jLabel6);
        jLabel6.setBounds(420, 110, 7, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("x10^");
        jLayeredPane2.add(jLabel4);
        jLabel4.setBounds(240, 110, 30, 14);
        jLayeredPane2.add(txtelevado1);
        txtelevado1.setBounds(280, 60, 129, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("C");
        jLayeredPane2.add(jLabel5);
        jLabel5.setBounds(420, 70, 7, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("x10^");
        jLayeredPane2.add(jLabel3);
        jLabel3.setBounds(240, 70, 30, 14);
        jLayeredPane2.add(txtf);
        txtf.setBounds(80, 140, 130, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("FUERZA(N)");
        jLayeredPane2.add(jLabel7);
        jLabel7.setBounds(10, 154, 60, 10);
        jLayeredPane2.add(txtcarga2);
        txtcarga2.setBounds(80, 100, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("CARGA 2");
        jLayeredPane2.add(jLabel2);
        jLabel2.setBounds(10, 110, 49, 14);

        RBELECTRONES.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RBELECTRONES.setForeground(new java.awt.Color(255, 0, 204));
        RBELECTRONES.setText("TRABAJAR CON ELECTRONES");
        RBELECTRONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBELECTRONESActionPerformed(evt);
            }
        });
        jLayeredPane2.add(RBELECTRONES);
        RBELECTRONES.setBounds(10, 30, 181, 23);
        jLayeredPane2.add(txtcarga1);
        txtcarga1.setBounds(80, 60, 130, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("CARGA 1");
        jLayeredPane2.add(jLabel1);
        jLabel1.setBounds(10, 70, 49, 14);

        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 460, 210));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\David Peñavasquez Va\\Desktop\\SODA (6).jpg")); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 480));

        jMenu1.setText("BY DAVID PEÑAVASQUEZ VASQUEZ");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCALCULARActionPerformed
 double Q1=Double.parseDouble(txtcarga1.getText());
       double Q2=Double.parseDouble(txtcarga2.getText());    
       double e1=Double.parseDouble(txtelevado1.getText());
        double e2=Double.parseDouble(txtelevado2.getText());
            double e3=Double.parseDouble(txtelevado3.getText());
              double f34=Double.parseDouble(txtf.getText());
 
        double f;
        f=(9*Q1*Q2);
        double f2;
        f2=9+e1+e2;
                double f3;
        f3=Math.pow(10, f2);
        double r;
        double r2;
        double r4;
        r4=Math.pow(10, e3);
        r2=(f*f3)/ (f34*r4);
        r=Math.sqrt(r2) ;
        String cal,l,l1;
        l=Double.toString(f);
        l1=Double.toString(f2);
        cal= Double.toString(r);
        TXTDIST.setText(cal);
        
                
    }//GEN-LAST:event_BTNCALCULARActionPerformed

    private void RBELECTRONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBELECTRONESActionPerformed
             BTNCALCULAR.setVisible(false);
    CALCULARE.setVisible(true);
    txtelevado1.setText("-19");
    txtelevado2.setText("-19");
    }//GEN-LAST:event_RBELECTRONESActionPerformed

    private void CALCULAREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULAREActionPerformed
        double Q1=Double.parseDouble(txtcarga1.getText());
       double Q2=Double.parseDouble(txtcarga2.getText());    
       double e1=Double.parseDouble(txtelevado1.getText());
        double e2=Double.parseDouble(txtelevado2.getText());
            double e3=Double.parseDouble(txtelevado3.getText());
              double f34=Double.parseDouble(txtf.getText());
 
        double f;
        f=(9*Q1*Q2*1.6021*1.6021);
        double f2;
        f2=9-19-19;
                double f3;
        f3=Math.pow(10, f2);
        double r;
        double r2;
        double r4;
        r4=Math.pow(10, e3);
        r2=(f*f3)/ (f34*r4);
        r=Math.sqrt(r2) ;
        String cal,l,l1;
        l=Double.toString(f);
        l1=Double.toString(f2);
        cal= Double.toString(r);
        TXTDIST.setText(cal);
    }//GEN-LAST:event_CALCULAREActionPerformed

    private void BTNLIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLIMPIARActionPerformed
 RBELECTRONES.setSelected(false);
        txtcarga1.setText("");
       txtcarga2.setText("");
       txtf.setText("");
       TXTDIST.setText("");
       txtelevado1.setText("");
       txtelevado2.setText("");
       txtelevado3.setText("");
       TXTDIST.setText("");
       CALCULARE.setVisible(false);
       BTNCALCULAR.setVisible(true);
               // TODO add your handling code here:
    }//GEN-LAST:event_BTNLIMPIARActionPerformed

    private void BTNSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIRActionPerformed
     Doscargas n= new Doscargas();
       if(BTNSALIR.isEnabled()){
          int p=JOptionPane.showConfirmDialog(null, "¿Estas seguro que deseas salir?","Mensaje",JOptionPane.YES_NO_OPTION);
          if(p==0){
              this.setVisible(false);
              this.dispose();}
       }
       
    }//GEN-LAST:event_BTNSALIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Distancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Distancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Distancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Distancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Distancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCALCULAR;
    private javax.swing.JButton BTNLIMPIAR;
    private javax.swing.JButton BTNSALIR;
    private javax.swing.JButton CALCULARE;
    private javax.swing.JRadioButton RBELECTRONES;
    private javax.swing.JTextField TXTDIST;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField txtcarga1;
    private javax.swing.JTextField txtcarga2;
    private javax.swing.JTextField txtelevado1;
    private javax.swing.JTextField txtelevado2;
    private javax.swing.JTextField txtelevado3;
    private javax.swing.JTextField txtf;
    // End of variables declaration//GEN-END:variables
}
