/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ColoresResistencias;

import javax.swing.JOptionPane;

/**
 *
 * @author David Peñavasquez Va
 */
public class Doscargas extends javax.swing.JFrame {

    /**
     * Creates new form Doscargas
     */
    public Doscargas() {
        initComponents();
        BTNCALCULARE.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        TXTCARGA1 = new javax.swing.JTextField();
        TXTCARGA2 = new javax.swing.JTextField();
        TXTELEVADO1 = new javax.swing.JTextField();
        TXTELEVADO2 = new javax.swing.JTextField();
        TXTDISTANCIA = new javax.swing.JTextField();
        BTNCALCULAR = new javax.swing.JButton();
        BTNLIMPIAR = new javax.swing.JButton();
        BTNSALIR = new javax.swing.JButton();
        TXTT = new javax.swing.JTextField();
        BTNCALCULARE = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TXTFUERZA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TXTELEVADO3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXTRESULTADO = new javax.swing.JTextField();
        RBF = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FISICA ll");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TXTCARGA1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TXTCARGA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCARGA1ActionPerformed(evt);
            }
        });
        getContentPane().add(TXTCARGA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 140, 60));

        TXTCARGA2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TXTCARGA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCARGA2ActionPerformed(evt);
            }
        });
        getContentPane().add(TXTCARGA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 140, 60));

        TXTELEVADO1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TXTELEVADO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTELEVADO1ActionPerformed(evt);
            }
        });
        getContentPane().add(TXTELEVADO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 140, 60));

        TXTELEVADO2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TXTELEVADO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTELEVADO2ActionPerformed(evt);
            }
        });
        getContentPane().add(TXTELEVADO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 140, 60));

        TXTDISTANCIA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TXTDISTANCIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTDISTANCIAActionPerformed(evt);
            }
        });
        getContentPane().add(TXTDISTANCIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 140, 60));

        BTNCALCULAR.setBackground(new java.awt.Color(0, 0, 255));
        BTNCALCULAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNCALCULAR.setForeground(new java.awt.Color(255, 255, 255));
        BTNCALCULAR.setText("CALCULAR");
        BTNCALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCALCULARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNCALCULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 127, 60));

        BTNLIMPIAR.setBackground(new java.awt.Color(255, 0, 0));
        BTNLIMPIAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNLIMPIAR.setForeground(new java.awt.Color(255, 255, 255));
        BTNLIMPIAR.setText("LIMPIAR CAMPOS");
        BTNLIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLIMPIARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNLIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, -1, 60));

        BTNSALIR.setBackground(new java.awt.Color(255, 0, 0));
        BTNSALIR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNSALIR.setForeground(new java.awt.Color(255, 255, 255));
        BTNSALIR.setText("SALIR");
        BTNSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(BTNSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 540, 130, 60));

        TXTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TXTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTActionPerformed(evt);
            }
        });
        getContentPane().add(TXTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 364, 140, 60));

        BTNCALCULARE.setBackground(new java.awt.Color(0, 51, 51));
        BTNCALCULARE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNCALCULARE.setForeground(new java.awt.Color(255, 255, 255));
        BTNCALCULARE.setText("CALCULAR(e)");
        BTNCALCULARE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCALCULAREActionPerformed(evt);
            }
        });
        getContentPane().add(BTNCALCULARE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 130, 60));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 204, 0))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 255));
        jLabel9.setText("EL RESULTADO FINAL ES :");
        jLayeredPane2.add(jLabel9);
        jLabel9.setBounds(10, 20, 234, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 255));
        jLabel8.setText("FUERZA");
        jLayeredPane2.add(jLabel8);
        jLabel8.setBounds(40, 50, 70, 22);

        TXTFUERZA.setEditable(false);
        jLayeredPane2.add(TXTFUERZA);
        TXTFUERZA.setBounds(130, 50, 112, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("x10^");
        jLayeredPane2.add(jLabel6);
        jLabel6.setBounds(270, 50, 48, 22);

        TXTELEVADO3.setEditable(false);
        jLayeredPane2.add(TXTELEVADO3);
        TXTELEVADO3.setBounds(330, 50, 116, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("Newtons.");
        jLayeredPane2.add(jLabel7);
        jLabel7.setBounds(460, 50, 86, 22);

        TXTRESULTADO.setEditable(false);
        jLayeredPane2.add(TXTRESULTADO);
        TXTRESULTADO.setBounds(210, 100, 165, 30);

        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 580, 170));

        RBF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RBF.setForeground(new java.awt.Color(255, 0, 204));
        RBF.setText("TRABAJAR CON ELECTRONES");
        RBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBFActionPerformed(evt);
            }
        });
        getContentPane().add(RBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\David Peñavasquez Va\\Desktop\\SODA (5).jpg")); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1160, 640));

        jMenu1.setText("BY DAVID PEÑAVASQUEZ VASQUEZ");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCALCULARActionPerformed
       double Q1=Double.parseDouble(TXTCARGA1.getText());
       double Q2=Double.parseDouble(TXTCARGA2.getText());
       double d1=Double.parseDouble(TXTDISTANCIA.getText());
       double e1=Double.parseDouble(TXTELEVADO1.getText());
        double e2=Double.parseDouble(TXTELEVADO2.getText());
        double Txtt=Double.parseDouble(TXTT.getText());
       
       double cuadrado;
       double f;
       
              
       double f2;
       f=(9*Q1*Q2)/Math.pow(d1, 2);
       cuadrado= (Txtt)*2;
       if(cuadrado<0){
           f2=((9+e1+e2)-cuadrado);
           
       }
       else{
           f2=(9+e1+e2-cuadrado);
       }
       double r;
       r=f*f2;
       String r1=Double.toString(r);
       if(r<0){
           TXTRESULTADO.setText("SE REPELEN");
           
       }
       else{
           TXTRESULTADO.setText("SE ATRAEN");
       }
          
       String Resul=Double.toString(f);
       String resultado2=Double.toString(f2);
       TXTFUERZA.setText(Resul);
       TXTELEVADO3.setText(resultado2);
       
      
      
       
    }//GEN-LAST:event_BTNCALCULARActionPerformed

    private void BTNLIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLIMPIARActionPerformed
       RBF.setSelected(false);
        TXTCARGA1.setText("");
       TXTCARGA2.setText("");
       TXTDISTANCIA.setText("");
       TXTELEVADO1.setText("");
       TXTELEVADO2.setText("");
       TXTT.setText("");
       TXTRESULTADO.setText("");
       TXTFUERZA.setText("");
       TXTELEVADO3.setText("");
       BTNCALCULARE.setVisible(false);
       BTNCALCULAR.setVisible(true);
       
       
    }//GEN-LAST:event_BTNLIMPIARActionPerformed

    private void BTNSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIRActionPerformed
        Doscargas n= new Doscargas();
       if(BTNSALIR.isEnabled()){
          int p=JOptionPane.showConfirmDialog(null, "¿Estas seguro que deseas salir?","Mensaje",JOptionPane.YES_NO_OPTION);
          if(p==0){
              this.setVisible(false);
              this.dispose();
            
           
              
            
              
          }    }
    }//GEN-LAST:event_BTNSALIRActionPerformed

    private void RBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBFActionPerformed
          BTNCALCULAR.setVisible(false);
    BTNCALCULARE.setVisible(true);
    TXTELEVADO1.setText("-19");
    TXTELEVADO2.setText("-19");
   
    }//GEN-LAST:event_RBFActionPerformed

    private void BTNCALCULAREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCALCULAREActionPerformed
        double Q1=Double.parseDouble(TXTCARGA1.getText());
       double Q2=Double.parseDouble(TXTCARGA2.getText());
       double d1=Double.parseDouble(TXTDISTANCIA.getText());
       double e1=Double.parseDouble(TXTELEVADO1.getText());
        double e2=Double.parseDouble(TXTELEVADO2.getText());
        double Txtt=Double.parseDouble(TXTT.getText());
       
       double cuadrado;
       double f;
       
              
       double f2;
       f=(9*Q1*Q2*1.6021*1.6021)/Math.pow(d1, 2);
       cuadrado= (Txtt)*2;
       if(cuadrado<0){
           f2=((9-19-19)-cuadrado);
           
       }
       else{
           f2=(9-19-19-cuadrado);
       }
       double r;
       r=f*f2;
       String r1=Double.toString(r);
       if(r<0){
           TXTRESULTADO.setText("SE ATRAEN");
           
       }
       else{
           TXTRESULTADO.setText("SE REPELEN");
       }
          
       String Resul=Double.toString(f);
       String resultado2=Double.toString(f2);
       TXTFUERZA.setText(Resul);
       TXTELEVADO3.setText(resultado2);
    }//GEN-LAST:event_BTNCALCULAREActionPerformed

    private void TXTCARGA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCARGA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCARGA1ActionPerformed

    private void TXTELEVADO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTELEVADO1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTELEVADO1ActionPerformed

    private void TXTCARGA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCARGA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCARGA2ActionPerformed

    private void TXTELEVADO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTELEVADO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTELEVADO2ActionPerformed

    private void TXTDISTANCIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTDISTANCIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTDISTANCIAActionPerformed

    private void TXTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doscargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doscargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doscargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doscargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doscargas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCALCULAR;
    private javax.swing.JButton BTNCALCULARE;
    private javax.swing.JButton BTNLIMPIAR;
    private javax.swing.JButton BTNSALIR;
    private javax.swing.JRadioButton RBF;
    private javax.swing.JTextField TXTCARGA1;
    private javax.swing.JTextField TXTCARGA2;
    private javax.swing.JTextField TXTDISTANCIA;
    private javax.swing.JTextField TXTELEVADO1;
    private javax.swing.JTextField TXTELEVADO2;
    private javax.swing.JTextField TXTELEVADO3;
    private javax.swing.JTextField TXTFUERZA;
    private javax.swing.JTextField TXTRESULTADO;
    private javax.swing.JTextField TXTT;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
