/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ColoresResistencias;

import javax.swing.JOptionPane;

/**
 *
 * @author David Peñavasquez Va
 */
public class Modulo extends javax.swing.JFrame {
  
    /**
     * Creates new form Modulo
     */
    public Modulo() {
        initComponents();
        BTNCALCULARE.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TXTCARGA1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTCARGA2 = new javax.swing.JTextField();
        TXTCARGA3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TXTELEVADO1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TXTELEVADO2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TXTELEVADO3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TXTDISTANCIA = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TXTDISTANCIA2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TXTT = new javax.swing.JTextField();
        TXTT2 = new javax.swing.JTextField();
        BTNCALCULAR = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        TXTFUERZA = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        FUERZA234 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TXTFUERZA2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        FUERZA2345 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TOTALF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        FT = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        RBELECTRONES = new javax.swing.JRadioButton();
        BTNCALCULARE = new javax.swing.JButton();
        BTNLIMPIA = new javax.swing.JButton();
        BTNSALIR = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel26 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FISICA ll");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("FUERZA QUE EXPERIMENTA CARGA 1 :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        getContentPane().add(TXTCARGA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 116, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("DEBIDO A :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("CARGA 2 :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("CARGA 3:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, -1, -1));
        getContentPane().add(TXTCARGA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 120, 115, -1));
        getContentPane().add(TXTCARGA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 158, 115, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("x10^");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));
        getContentPane().add(TXTELEVADO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 127, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("C");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 10, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("x10^");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 123, -1, -1));
        getContentPane().add(TXTELEVADO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 120, 152, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("x10^");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 161, -1, -1));
        getContentPane().add(TXTELEVADO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 158, 152, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("C");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 123, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("C");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 161, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("DISTANCIA(m)  CARGA 1   ------ CARGA 2");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        getContentPane().add(TXTDISTANCIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 76, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("DISTANCIA(m)  CARGA 1   ------ CARGA 3");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, 230, -1));
        getContentPane().add(TXTDISTANCIA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 76, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("x10^");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("x10^");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));
        getContentPane().add(TXTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 79, -1));
        getContentPane().add(TXTT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 79, -1));

        BTNCALCULAR.setBackground(new java.awt.Color(0, 0, 255));
        BTNCALCULAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNCALCULAR.setForeground(new java.awt.Color(255, 255, 255));
        BTNCALCULAR.setText("CALCULAR");
        BTNCALCULAR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                BTNCALCULARFocusLost(evt);
            }
        });
        BTNCALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCALCULARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNCALCULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 110, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 255, 255));
        jLabel15.setText("FUERZA DE CARGA 1  A CARGA 2");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));
        getContentPane().add(TXTFUERZA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 150, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 204));
        jLabel16.setText("x10^");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        FUERZA234.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FUERZA234ActionPerformed(evt);
            }
        });
        getContentPane().add(FUERZA234, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 83, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 255, 255));
        jLabel17.setText("FUERZA DE CARGA 1 A CARGA 3");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 368, -1, -1));
        getContentPane().add(TXTFUERZA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 150, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 255, 255));
        jLabel18.setText("x10^");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));
        getContentPane().add(FUERZA2345, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 83, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 255, 255));
        jLabel19.setText("FUERZA RESULTANTE :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 399, -1, -1));
        getContentPane().add(TOTALF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 150, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 204, 255));
        jLabel20.setText("x10^");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));
        getContentPane().add(FT, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 83, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("N");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("N");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("N");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, -1));

        RBELECTRONES.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RBELECTRONES.setForeground(new java.awt.Color(255, 0, 153));
        RBELECTRONES.setText("TRABAJAR CON ELECTRONES");
        RBELECTRONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBELECTRONESActionPerformed(evt);
            }
        });
        getContentPane().add(RBELECTRONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        BTNCALCULARE.setText("CALCULAR(e)");
        BTNCALCULARE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCALCULAREActionPerformed(evt);
            }
        });
        getContentPane().add(BTNCALCULARE, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 108, -1));

        BTNLIMPIA.setBackground(new java.awt.Color(255, 0, 0));
        BTNLIMPIA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNLIMPIA.setForeground(new java.awt.Color(255, 255, 255));
        BTNLIMPIA.setText("LIMPIAR DATOS");
        BTNLIMPIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLIMPIAActionPerformed(evt);
            }
        });
        getContentPane().add(BTNLIMPIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        BTNSALIR.setBackground(new java.awt.Color(255, 0, 0));
        BTNSALIR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNSALIR.setForeground(new java.awt.Color(255, 255, 255));
        BTNSALIR.setText("SALIR");
        BTNSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(BTNSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 90, -1));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESAR DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 204, 0))); // NOI18N
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 20, 660, 270));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 204, 0))); // NOI18N
        jLayeredPane2.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 620, 120));

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\David Peñavasquez Va\\Downloads\\SODA (7).jpg")); // NOI18N
        jLabel26.setText("jLabel26");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 530));

        jMenu2.setText("BY DAVID PEÑAVASQUEZ VASQUEZ");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCALCULARActionPerformed
          double Q1=Double.parseDouble(TXTCARGA1.getText());
       double Q2=Double.parseDouble(TXTCARGA2.getText());
       double d1=Double.parseDouble(TXTDISTANCIA.getText());
       double e1=Double.parseDouble(TXTELEVADO1.getText());
        double e2=Double.parseDouble(TXTELEVADO2.getText());
        double Txtt=Double.parseDouble(TXTT.getText());
          double Q3=Double.parseDouble(TXTCARGA3.getText());
           double e3=Double.parseDouble(TXTELEVADO3.getText());
           double d2=Double.parseDouble(TXTDISTANCIA2.getText());
              double Txtt2=Double.parseDouble(TXTT2.getText());
           
       double cuadrado2;
       double cuadrado;
       double f;
       double f3;
       double f4;
        double tot;     
        double tot2;
       double f2;
       f=(9*Q1*Q2)/Math.pow(d1, 2);
       cuadrado= (Txtt)*2;
       if(cuadrado<0){
           f2=((9+e1+e2)-cuadrado);
           
       }
       else{
           f2=(9+e1+e2-cuadrado);
       }
        String Resul=Double.toString(f);
       String resultado2=Double.toString(f2);
       TXTFUERZA.setText(Resul);
       FUERZA234.setText(resultado2);
       f3=(9*Q1*Q3)/Math.pow(d2, 2);
        cuadrado2= (Txtt2)*2;
       if(cuadrado2<0){
           f4=((9+e1+e3)-cuadrado2);
           
       }
       else{
           f4=(9+e1+e3-cuadrado);
       }
        String Resul2=Double.toString(f3);
       String resultado3=Double.toString(f4);
       TXTFUERZA2.setText(Resul2);
       FUERZA2345.setText(resultado3);
       
       tot=f-f3;
       tot2=f2+f4;
       String resp= Double.toString(tot);
       String resp2=Double.toString(tot2);
       TOTALF.setText(resp);
       FT.setText(resp2);
    
      
    }//GEN-LAST:event_BTNCALCULARActionPerformed

    private void RBELECTRONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBELECTRONESActionPerformed
    BTNCALCULAR.setVisible(false);
    BTNCALCULARE.setVisible(true);
    TXTELEVADO1.setText("-19");
    TXTELEVADO2.setText("-19");
    TXTELEVADO3.setText("-19");
    
       
    }//GEN-LAST:event_RBELECTRONESActionPerformed

    private void BTNCALCULARFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BTNCALCULARFocusLost
       
    }//GEN-LAST:event_BTNCALCULARFocusLost

    private void BTNCALCULAREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCALCULAREActionPerformed
        double Q1=Double.parseDouble(TXTCARGA1.getText());
       double Q2=Double.parseDouble(TXTCARGA2.getText());
       double d1=Double.parseDouble(TXTDISTANCIA.getText());
       double e1=Double.parseDouble(TXTELEVADO1.getText());
        double e2=Double.parseDouble(TXTELEVADO2.getText());
        double Txtt=Double.parseDouble(TXTT.getText());
          double Q3=Double.parseDouble(TXTCARGA3.getText());
           double e3=Double.parseDouble(TXTELEVADO3.getText());
           double d2=Double.parseDouble(TXTDISTANCIA2.getText());
              double Txtt2=Double.parseDouble(TXTT2.getText());
           
       double cuadrado2;
       double cuadrado;
       double f;
       double f3;
       double f4;
        double tot;     
        double tot2;
       double f2;
       f=(9*Q1*Q2*1.6021*1.6021)/Math.pow(d1, 2);
       cuadrado= (Txtt)*2;
       if(cuadrado<0){
           f2=((9-19-19)-cuadrado);
           
       }
       else{
           f2=(9-19-19-cuadrado);
       }
        String Resul=Double.toString(f);
       String resultado2=Double.toString(f2);
       TXTFUERZA.setText(Resul);
       FUERZA234.setText(resultado2);
       f3=(9*Q1*Q3*1.6021*1.6021)/Math.pow(d2, 2);
        cuadrado2= (Txtt2)*2;
       if(cuadrado2<0){
           f4=((9-19-19)-cuadrado2);
           
       }
       else{
           f4=(9-19-19-cuadrado);
       }
        String Resul2=Double.toString(f3);
       String resultado3=Double.toString(f4);
       TXTFUERZA2.setText(Resul2);
       FUERZA2345.setText(resultado3);
       
       tot=f-f3;
       tot2=f2+f4;
       String resp= Double.toString(tot);
       String resp2=Double.toString(tot2);
       TOTALF.setText(resp);
       FT.setText(resp2);
    }//GEN-LAST:event_BTNCALCULAREActionPerformed

    private void BTNLIMPIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLIMPIAActionPerformed
 
        
        
        RBELECTRONES.setSelected(false);
      
        TXTCARGA1.setText("");
        TXTCARGA2.setText("");
        TXTCARGA3.setText("");
        TXTELEVADO1.setText("");
        TXTELEVADO2.setText("");
        TXTELEVADO3.setText("");
        TXTDISTANCIA.setText("");
        TXTDISTANCIA2.setText("");
        TXTT.setText("");
        TXTT2.setText("");
        FUERZA234.setText("");
        FUERZA2345.setText("");
        TOTALF.setText("");
       TXTFUERZA.setText("");
       TXTFUERZA2.setText("");
        FT.setText("");
        BTNCALCULARE.setVisible(false);
        BTNCALCULAR.setVisible(true);
        
    }//GEN-LAST:event_BTNLIMPIAActionPerformed

    private void BTNSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIRActionPerformed
         Modulo n= new Modulo();
       if(BTNSALIR.isEnabled()){
          int p=JOptionPane.showConfirmDialog(null, "¿Estas seguro que deseas salir?","Mensaje",JOptionPane.YES_NO_OPTION);
          if(p==0){
              this.setVisible(false);
              this.dispose();}
       }
    }//GEN-LAST:event_BTNSALIRActionPerformed

    private void FUERZA234ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FUERZA234ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FUERZA234ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCALCULAR;
    private javax.swing.JButton BTNCALCULARE;
    private javax.swing.JButton BTNLIMPIA;
    private javax.swing.JButton BTNSALIR;
    private javax.swing.JTextField FT;
    private javax.swing.JTextField FUERZA234;
    private javax.swing.JTextField FUERZA2345;
    private javax.swing.JRadioButton RBELECTRONES;
    private javax.swing.JTextField TOTALF;
    private javax.swing.JTextField TXTCARGA1;
    private javax.swing.JTextField TXTCARGA2;
    private javax.swing.JTextField TXTCARGA3;
    private javax.swing.JTextField TXTDISTANCIA;
    private javax.swing.JTextField TXTDISTANCIA2;
    private javax.swing.JTextField TXTELEVADO1;
    private javax.swing.JTextField TXTELEVADO2;
    private javax.swing.JTextField TXTELEVADO3;
    private javax.swing.JTextField TXTFUERZA;
    private javax.swing.JTextField TXTFUERZA2;
    private javax.swing.JTextField TXTT;
    private javax.swing.JTextField TXTT2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
