/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ColoresResistencias;

import Interfaces.Menu;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author David Peñavasquez Va
 */
public class probando extends javax.swing.JFrame {

    /**
     * Creates new form probando
     */
    public probando() {
        initComponents();
        this.setLocationRelativeTo(null);
       
               BTNC3.setBackground(Color.black);
                    BTNC4.setBackground(new Color(153,51,0));
                     BTNC5.setBackground(Color.red);
                     BTNC6.setBackground(Color.orange);
                     BTNC7.setBackground(Color.yellow);
                     BTNC11.setBackground(Color.green);
                     BTNC9.setBackground(new Color(102,0,102));
                     BTNC10.setBackground(new Color(102,102,102));
                     BTNC8.setBackground(Color.blue);
                     BTNC12.setBackground(Color.white);
                   
          
               C15.setBackground(Color.black);
                    C16.setBackground(new Color(153,51,0));
                     C17.setBackground(Color.red);
                     C18.setBackground(Color.orange);
                     C19.setBackground(Color.yellow);
                     C20.setBackground(Color.green);
                     C21.setBackground(Color.blue);
                     C22.setBackground(new Color(102,0,102));
                     C23.setBackground(new Color(102,102,102));
                     C24.setBackground(Color.white);
                    
       
               C27.setBackground(Color.black);
                    C28.setBackground(new Color(153,51,0));
                     C29.setBackground(Color.red);
                     C30.setBackground(Color.orange);
                     C31.setBackground(Color.yellow);
                     C32.setBackground(Color.green);
                     C33.setBackground(Color.blue);
                     C34.setBackground(new Color(102,0,102));
                     C35.setBackground(new Color(102,102,102));
                     C36.setBackground(Color.white);
                    
          
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        SALIR = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BTNC12 = new javax.swing.JButton();
        BTNC10 = new javax.swing.JButton();
        BTNC9 = new javax.swing.JButton();
        BTNC8 = new javax.swing.JButton();
        BTNC11 = new javax.swing.JButton();
        BTNC7 = new javax.swing.JButton();
        BTNC6 = new javax.swing.JButton();
        BTNC5 = new javax.swing.JButton();
        BTNC3 = new javax.swing.JButton();
        BTNC4 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        C24 = new javax.swing.JButton();
        C23 = new javax.swing.JButton();
        C22 = new javax.swing.JButton();
        C21 = new javax.swing.JButton();
        C20 = new javax.swing.JButton();
        C19 = new javax.swing.JButton();
        C18 = new javax.swing.JButton();
        C17 = new javax.swing.JButton();
        C16 = new javax.swing.JButton();
        C15 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        C36 = new javax.swing.JButton();
        C35 = new javax.swing.JButton();
        C34 = new javax.swing.JButton();
        C33 = new javax.swing.JButton();
        C32 = new javax.swing.JButton();
        C31 = new javax.swing.JButton();
        C30 = new javax.swing.JButton();
        C29 = new javax.swing.JButton();
        C28 = new javax.swing.JButton();
        C27 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TOLERANCIA = new javax.swing.JLabel();
        CBMULTIPLICADOR = new javax.swing.JComboBox<>();
        CBTOLERANCIA = new javax.swing.JComboBox<>();
        RES1 = new javax.swing.JTextField();
        RES2 = new javax.swing.JTextField();
        RES3 = new javax.swing.JTextField();
        RES4 = new javax.swing.JTextField();
        RES5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AREA = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        BAND = new javax.swing.JComboBox<>();
        J1 = new javax.swing.JTextField();
        J5 = new javax.swing.JTextField();
        J4 = new javax.swing.JTextField();
        J3 = new javax.swing.JTextField();
        J2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FISICA ll");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        SALIR.setBackground(new java.awt.Color(0, 153, 153));
        SALIR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SALIR.setForeground(new java.awt.Color(255, 255, 255));
        SALIR.setText("REGRESAR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 120, 30));

        jButton5.setBackground(new java.awt.Color(0, 153, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("REINICIAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 120, 30));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 153, 153));
        jLabel41.setText("CODIGO DE RESISTENCIA DE COLORES");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("BANDA 1");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Negro");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Marron");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Rojo");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Naranja");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Amarillo");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Verde");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Azul");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Violeta");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Gris");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Blanco");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        BTNC12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC12ActionPerformed(evt);
            }
        });
        jPanel4.add(BTNC12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 70, 20));

        BTNC10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC10ActionPerformed(evt);
            }
        });
        jPanel4.add(BTNC10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 70, 20));

        BTNC9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC9ActionPerformed(evt);
            }
        });
        jPanel4.add(BTNC9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 70, 20));

        BTNC8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC8ActionPerformed(evt);
            }
        });
        jPanel4.add(BTNC8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 70, 20));

        BTNC11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC11ActionPerformed(evt);
            }
        });
        jPanel4.add(BTNC11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 70, 20));

        BTNC7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC7ActionPerformed(evt);
            }
        });
        jPanel4.add(BTNC7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 70, 20));

        BTNC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC6ActionPerformed(evt);
            }
        });
        jPanel4.add(BTNC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 70, 20));

        BTNC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC5ActionPerformed(evt);
            }
        });
        jPanel4.add(BTNC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 70, 20));

        BTNC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC3ActionPerformed(evt);
            }
        });
        jPanel4.add(BTNC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 70, 20));

        BTNC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNC4ActionPerformed(evt);
            }
        });
        jPanel4.add(BTNC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 70, 20));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setText("BANDA 2");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Negro");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Marron");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Rojo");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Naranja");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Amarillo");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Verde");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Azul");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Violeta");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Gris");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Blanco");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        C24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C24ActionPerformed(evt);
            }
        });
        jPanel4.add(C24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 70, 20));

        C23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C23ActionPerformed(evt);
            }
        });
        jPanel4.add(C23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 70, 20));

        C22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C22ActionPerformed(evt);
            }
        });
        jPanel4.add(C22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 70, 20));

        C21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C21ActionPerformed(evt);
            }
        });
        jPanel4.add(C21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 70, 20));

        C20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C20ActionPerformed(evt);
            }
        });
        jPanel4.add(C20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 70, 20));

        C19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C19ActionPerformed(evt);
            }
        });
        jPanel4.add(C19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 70, 20));

        C18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C18ActionPerformed(evt);
            }
        });
        jPanel4.add(C18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 70, 20));

        C17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C17ActionPerformed(evt);
            }
        });
        jPanel4.add(C17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 70, 20));

        C16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C16ActionPerformed(evt);
            }
        });
        jPanel4.add(C16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 70, 20));

        C15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C15ActionPerformed(evt);
            }
        });
        jPanel4.add(C15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 70, 20));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("BANDA 3");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Negro");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Marron");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Rojo");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Naranja");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Amarillo");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Verde");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Azul");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Violeta");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Gris");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Blanco");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, -1));

        C36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C36ActionPerformed(evt);
            }
        });
        jPanel4.add(C36, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 70, 20));

        C35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C35ActionPerformed(evt);
            }
        });
        jPanel4.add(C35, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 70, 20));

        C34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C34ActionPerformed(evt);
            }
        });
        jPanel4.add(C34, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 70, 20));

        C33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C33ActionPerformed(evt);
            }
        });
        jPanel4.add(C33, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 70, 20));

        C32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C32ActionPerformed(evt);
            }
        });
        jPanel4.add(C32, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 70, 20));

        C31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C31ActionPerformed(evt);
            }
        });
        jPanel4.add(C31, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 70, 20));

        C30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C30ActionPerformed(evt);
            }
        });
        jPanel4.add(C30, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 70, 20));

        C29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C29ActionPerformed(evt);
            }
        });
        jPanel4.add(C29, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 70, 20));

        C28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C28ActionPerformed(evt);
            }
        });
        jPanel4.add(C28, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 70, 20));

        C27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C27ActionPerformed(evt);
            }
        });
        jPanel4.add(C27, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 70, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MULTIPLICADOR");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 130, 20));

        TOLERANCIA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TOLERANCIA.setText("TOLERANCIA");
        jPanel4.add(TOLERANCIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, -1, 20));

        CBMULTIPLICADOR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CBMULTIPLICADOR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MULTIPLICADOR", "PLATA", "ORO", "NEGRO", "MARRON", "ROJO", "NARANJA", "AMARILLO", "VERDE", "AZUL", " " }));
        CBMULTIPLICADOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMULTIPLICADORActionPerformed(evt);
            }
        });
        jPanel4.add(CBMULTIPLICADOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 70, 200));

        CBTOLERANCIA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CBTOLERANCIA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TOLERANCIA", "PLATA", "ORO", "MARRON", "ROJO", "NARANJA", "AMARILLO", "VERDE", "SIN COLOR", " " }));
        CBTOLERANCIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTOLERANCIAActionPerformed(evt);
            }
        });
        jPanel4.add(CBTOLERANCIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 70, 200));

        RES1.setEditable(false);
        RES1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RES1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RES1ActionPerformed(evt);
            }
        });
        jPanel4.add(RES1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 120, 30));

        RES2.setEditable(false);
        RES2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(RES2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 120, 30));

        RES3.setEditable(false);
        RES3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(RES3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 120, 30));

        RES4.setEditable(false);
        RES4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(RES4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 70, 30));

        RES5.setEditable(false);
        RES5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(RES5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 70, 30));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 130, 30));

        AREA.setEditable(false);
        AREA.setColumns(20);
        AREA.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        AREA.setRows(5);
        jScrollPane1.setViewportView(AREA);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 360, 60));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("KΩ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 80, 30));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("MΩ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 80, 30));

        BAND.setBackground(new java.awt.Color(0, 153, 153));
        BAND.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BAND.setForeground(new java.awt.Color(255, 255, 255));
        BAND.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÚMERO DE BANDAS:", "DOS BANDAS", "CUATRO BANDAS" }));
        BAND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BANDActionPerformed(evt);
            }
        });
        jPanel4.add(BAND, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, 30));

        J1.setEditable(false);
        J1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J1ActionPerformed(evt);
            }
        });
        jPanel4.add(J1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 20, 90));

        J5.setEditable(false);
        J5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J5ActionPerformed(evt);
            }
        });
        jPanel4.add(J5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 20, 90));

        J4.setEditable(false);
        J4.setHighlighter(null);
        J4.setRequestFocusEnabled(false);
        J4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J4ActionPerformed(evt);
            }
        });
        jPanel4.add(J4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 20, 80));

        J3.setEditable(false);
        jPanel4.add(J3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 20, 80));

        J2.setEditable(false);
        jPanel4.add(J2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 20, 80));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Resistor.png"))); // NOI18N
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 910, 630));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 920, 590));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void J4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J4ActionPerformed

    private void J1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J1ActionPerformed
      
    }//GEN-LAST:event_J1ActionPerformed

    private void BTNC8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC8ActionPerformed
        J1.setBackground(Color.blue);
           int r=6;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);
    }//GEN-LAST:event_BTNC8ActionPerformed

    private void CBMULTIPLICADORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMULTIPLICADORActionPerformed
     
      if(CBMULTIPLICADOR.getSelectedIndex()==1){
        CBMULTIPLICADOR.setBackground(new Color(153,153,153));
         J4.setBackground(new Color(153,153,153));
         double r= 0.01;
         String res;
         res=Double.toString(r);
         RES4.setText(res);
         
         
        
      }
      if(CBMULTIPLICADOR.getSelectedIndex()==2){
        CBMULTIPLICADOR.setBackground(new Color(255,204,51));
        J4.setBackground(new Color(255,204,51));
            double r= 0.1;
         String res;
         res=Double.toString(r);
         RES4.setText(res);
      }
      if(CBMULTIPLICADOR.getSelectedIndex()==3){
        CBMULTIPLICADOR.setBackground(Color.black);
       J4.setBackground(Color.black);
           double r= 1;
         String res;
         res=Double.toString(r);
         RES4.setText(res);
      }
      if(CBMULTIPLICADOR.getSelectedIndex()==4){
        CBMULTIPLICADOR.setBackground(new Color(153,51,0));
          J4.setBackground(new Color(153,51,0));
             double r= 10;
         String res;
         res=Double.toString(r);
         RES4.setText(res);
      }
      if(CBMULTIPLICADOR.getSelectedIndex()==5){
        CBMULTIPLICADOR.setBackground(Color.red);
          J4.setBackground(Color.red);
                double r= 100;
         String res;
         res=Double.toString(r);
         RES4.setText(res);
      }
      if(CBMULTIPLICADOR.getSelectedIndex()==6){
        CBMULTIPLICADOR.setBackground(Color.orange);
         J4.setBackground(Color.orange);
              double r= 1000;
         String res;
         res=Double.toString(r);
         RES4.setText(res);
        
      }
      if(CBMULTIPLICADOR.getSelectedIndex()==7){
        CBMULTIPLICADOR.setBackground(Color.yellow);
        J4.setBackground(Color.yellow);
             double r= 10000;
         String res;
         res=Double.toString(r);
         RES4.setText(res);
      }
      if(CBMULTIPLICADOR.getSelectedIndex()==8){
        CBMULTIPLICADOR.setBackground(Color.green);
        J4.setBackground(Color.green);
              double r= 1000000;
         String res;
         res=Double.toString(r);
         RES4.setText(res);
      }
      if(CBMULTIPLICADOR.getSelectedIndex()==9){
        CBMULTIPLICADOR.setBackground(Color.blue);
        J4.setBackground(Color.blue);
             double r= 10000000;
         String res;
         res=Double.toString(r);
         RES4.setText(res);
      }
    
        
    }//GEN-LAST:event_CBMULTIPLICADORActionPerformed

    private void CBTOLERANCIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTOLERANCIAActionPerformed
         if(CBTOLERANCIA.getSelectedIndex()==1){
        CBTOLERANCIA.setBackground(new Color(153,153,153));
        J5.setBackground(new Color(153,153,153));
             double r= 0.1;
         String res;
         res=Double.toString(r);
         RES5.setText(res);
         
      }
      if(CBTOLERANCIA.getSelectedIndex()==2){
        CBTOLERANCIA.setBackground(new Color(255,204,51));
          J5.setBackground(new Color(255,204,51));
             double r= 0.05;
         String res;
         res=Double.toString(r);
         RES5.setText(res);
      }
      if(CBTOLERANCIA.getSelectedIndex()==3){
        CBTOLERANCIA.setBackground(new Color(153,51,0));
        J5.setBackground(new Color(153,51,0));
          double r= 0.01;
         String res;
         res=Double.toString(r);
         RES5.setText(res);
      }
      if(CBTOLERANCIA.getSelectedIndex()==4){
        CBTOLERANCIA.setBackground(Color.red);
        J5.setBackground(Color.red);
          double r= 0.02;
         String res;
         res=Double.toString(r);
         RES5.setText(res);
      }
      if(CBTOLERANCIA.getSelectedIndex()==5){
        CBTOLERANCIA.setBackground(Color.orange);
        J5.setBackground(Color.orange);
           double r= 0.03;
         String res;
         res=Double.toString(r);
         RES5.setText(res);
      }
      if(CBTOLERANCIA.getSelectedIndex()==6){
       CBTOLERANCIA.setBackground(Color.yellow);
       J5.setBackground(Color.yellow);
         double r= 0.04;
         String res;
         res=Double.toString(r);
         RES5.setText(res);
        
      }
      if(CBTOLERANCIA.getSelectedIndex()==7){
        CBTOLERANCIA.setBackground(Color.green);
        J5.setBackground(Color.green);
           double r= 0.005;
         String res;
         res=Double.toString(r);
         RES5.setText(res);
      }
       if(CBTOLERANCIA.getSelectedIndex()==8){
        CBTOLERANCIA.setBackground(Color.WHITE);
        J5.setBackground(Color.WHITE);
          double r= 0.2;
         String res;
         res=Double.toString(r);
         RES5.setText(res);
      }
   
    }//GEN-LAST:event_CBTOLERANCIAActionPerformed

    private void BTNC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC3ActionPerformed
        J1.setBackground(Color.black);
        int r=0;
        String res;
        res=Integer.toString(r);
        
        RES1.setText(res);
    }//GEN-LAST:event_BTNC3ActionPerformed

    private void BTNC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC4ActionPerformed
        J1.setBackground(new Color(153,51,0));
        int r=1;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);
    }//GEN-LAST:event_BTNC4ActionPerformed

    private void BTNC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC5ActionPerformed
    J1.setBackground(Color.red);
        int r=2;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);
    }//GEN-LAST:event_BTNC5ActionPerformed

    private void BTNC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC6ActionPerformed
        J1.setBackground(Color.orange);
            int r=3;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);
    }//GEN-LAST:event_BTNC6ActionPerformed

    private void BTNC7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC7ActionPerformed
        J1.setBackground(Color.yellow);
           int r=4;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);
    }//GEN-LAST:event_BTNC7ActionPerformed

    private void BTNC11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC11ActionPerformed
        J1.setBackground(Color.green);
            int r=5;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);
    }//GEN-LAST:event_BTNC11ActionPerformed

    private void BTNC9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC9ActionPerformed
      J1.setBackground(new Color(102,0,102));
        int r=7;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);
                    
    }//GEN-LAST:event_BTNC9ActionPerformed

    private void BTNC10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC10ActionPerformed
      J1.setBackground(new Color(102,102,102));
          int r=8;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);
    }//GEN-LAST:event_BTNC10ActionPerformed

    private void BTNC12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNC12ActionPerformed
        J1.setBackground(Color.white);
            int r=9;
            String res;
        res=Integer.toString(r);
        
        RES1.setText(res);
    }//GEN-LAST:event_BTNC12ActionPerformed

    private void C15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C15ActionPerformed
       J2.setBackground(Color.black);
           int r=0;
        String res;
        res=Integer.toString(r);
        
        RES2.setText(res);
    }//GEN-LAST:event_C15ActionPerformed

    private void C16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C16ActionPerformed
         J2.setBackground(new Color(153,51,0));
              int r=1;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);
    }//GEN-LAST:event_C16ActionPerformed

    private void C17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C17ActionPerformed
       J2.setBackground(Color.red);
            int r=2;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);
    }//GEN-LAST:event_C17ActionPerformed

    private void C18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C18ActionPerformed
         J2.setBackground(Color.orange);
             int r=3;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);
    }//GEN-LAST:event_C18ActionPerformed

    private void C19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C19ActionPerformed
       J2.setBackground(Color.yellow);
            int r=4;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);
    }//GEN-LAST:event_C19ActionPerformed

    private void C20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C20ActionPerformed
      J2.setBackground(Color.green);
           int r=5;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);
    }//GEN-LAST:event_C20ActionPerformed

    private void C21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C21ActionPerformed
         J2.setBackground(Color.blue);
             int r=6;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);
    }//GEN-LAST:event_C21ActionPerformed

    private void C22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C22ActionPerformed
        J2.setBackground(new Color(102,0,102));
           int r=7;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);
    }//GEN-LAST:event_C22ActionPerformed

    private void C23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C23ActionPerformed
       J2.setBackground(new Color(102,102,102));
          int r=8;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);
    }//GEN-LAST:event_C23ActionPerformed

    private void C24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C24ActionPerformed
       J2.setBackground(Color.white);
             int r=9;
            String res;
        res=Integer.toString(r);
        
        RES2.setText(res);
    }//GEN-LAST:event_C24ActionPerformed

    private void C27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C27ActionPerformed
        J3.setBackground(Color.black);
          
           int r=0;
        String res;
        res=Integer.toString(r);
        
        RES3.setText(res);
    }//GEN-LAST:event_C27ActionPerformed

    private void C28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C28ActionPerformed
         J3.setBackground(new Color(153,51,0));
                int r=1;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);
    }//GEN-LAST:event_C28ActionPerformed

    private void C29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C29ActionPerformed
        J3.setBackground(Color.red);
             int r=2;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);
    }//GEN-LAST:event_C29ActionPerformed

    private void C30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C30ActionPerformed
         J3.setBackground(Color.orange);
                int r=3;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);
    }//GEN-LAST:event_C30ActionPerformed

    private void C31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C31ActionPerformed
        J3.setBackground(Color.yellow);
               int r=4;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);
    }//GEN-LAST:event_C31ActionPerformed

    private void C32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C32ActionPerformed
           J3.setBackground(Color.green);
                int r=5;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);
    }//GEN-LAST:event_C32ActionPerformed

    private void C33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C33ActionPerformed
      J3.setBackground(Color.blue);
             int r=6;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);
    }//GEN-LAST:event_C33ActionPerformed

    private void C34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C34ActionPerformed
         J3.setBackground(new Color(102,0,102));
            int r=7;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);
    }//GEN-LAST:event_C34ActionPerformed

    private void C35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C35ActionPerformed
     J3.setBackground(new Color(102,102,102));
         int r=8;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);
    }//GEN-LAST:event_C35ActionPerformed

    private void C36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C36ActionPerformed
       J3.setBackground(Color.white);
             int r=9;
            String res;
        res=Integer.toString(r);
        
        RES3.setText(res);
    }//GEN-LAST:event_C36ActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    private void RES1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RES1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RES1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

   int campo1=Integer.parseInt(RES1.getText());
   int campo2=Integer.parseInt(RES2.getText());
   int campo3=Integer.parseInt(RES3.getText());
   double campo4=Double.parseDouble(RES4.getText());
    double campo5=Double.parseDouble(RES5.getText());
  
  
 String campoo1=Integer.toString(campo1);
 String campoo2=Integer.toString(campo2);
 String campoo3=Integer.toString(campo3);
  String campoo4=Double.toString(campo4);
    String campoo5=Double.toString(campo5);
  

 
 String conca=campoo1.concat(campoo2.concat(campoo3));
   int result2= Integer.parseInt(conca);
   double resolv= result2*campo4;
   double resolv2= resolv*campo5;
   String nuevo=Double.toString(resolv);
     String nuevo1=Double.toString(resolv2);
    AREA.append("LA RESISTENCIA ES :");
    AREA.append(System.getProperty("line.separator"));
    AREA.append(nuevo+"  +/-  "+ nuevo1 +"‎Ω");
    
   
   
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int campo1=Integer.parseInt(RES1.getText());
   int campo2=Integer.parseInt(RES2.getText());
   int campo3=Integer.parseInt(RES3.getText());
   double campo4=Double.parseDouble(RES4.getText());
    double campo5=Double.parseDouble(RES5.getText());
  
  
 String campoo1=Integer.toString(campo1);
 String campoo2=Integer.toString(campo2);
 String campoo3=Integer.toString(campo3);
  String campoo4=Double.toString(campo4);
    String campoo5=Double.toString(campo5);
  

 
 String conca=campoo1.concat(campoo2.concat(campoo3));
   int result2= Integer.parseInt(conca);
   double resolv= result2*campo4;
   double resolv2= resolv*campo5;
  double convertidor=resolv/1000;
  double convertidor2=resolv2/1000;
  JOptionPane.showMessageDialog(null, " LA RESPUESTA EN K‎Ω: " + convertidor+"  +/-  "+convertidor2+" K‎Ω ");
     
     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int campo1=Integer.parseInt(RES1.getText());
   int campo2=Integer.parseInt(RES2.getText());
   int campo3=Integer.parseInt(RES3.getText());
   double campo4=Double.parseDouble(RES4.getText());
    double campo5=Double.parseDouble(RES5.getText());
  
  
 String campoo1=Integer.toString(campo1);
 String campoo2=Integer.toString(campo2);
 String campoo3=Integer.toString(campo3);
  String campoo4=Double.toString(campo4);
    String campoo5=Double.toString(campo5);
  

 
 String conca=campoo1.concat(campoo2.concat(campoo3));
   int result2= Integer.parseInt(conca);
   double resolv= result2*campo4;
   double resolv2= resolv*campo5;
  double convertidor=resolv/1000000;
  double convertidor2=resolv2/1000000;
  JOptionPane.showMessageDialog(null, " LA RESPUESTA EN MΩ: " + convertidor+"  +/-  "+convertidor2+" MΩ ");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        J1.setBackground(Color.white);
           J2.setBackground(Color.white);
              J3.setBackground(Color.white);
                 J4.setBackground(Color.white);
                    J5.setBackground(Color.white);
                    CBMULTIPLICADOR.setSelectedIndex(0);
                     CBMULTIPLICADOR.setBackground(Color.white);
                    CBTOLERANCIA.setSelectedIndex(0);
                    CBTOLERANCIA.setBackground(Color.white);
                    
                    RES1.setText("");
                    RES2.setText("");
                    RES3.setText("");
                    RES4.setText("");
                    RES5.setText("");
                    AREA.setText("");
                    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void J5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J5ActionPerformed

    private void BANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BANDActionPerformed
        Banda2 n= new Banda2();
        Cuatrobandas k= new Cuatrobandas();
        if(BAND.getSelectedIndex()==1){
            n.setVisible(true);
            dispose();

        }
         if(BAND.getSelectedIndex()==2){
            k.setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_BANDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(probando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(probando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(probando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(probando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new probando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AREA;
    private javax.swing.JComboBox<String> BAND;
    private javax.swing.JButton BTNC10;
    private javax.swing.JButton BTNC11;
    private javax.swing.JButton BTNC12;
    private javax.swing.JButton BTNC3;
    private javax.swing.JButton BTNC4;
    private javax.swing.JButton BTNC5;
    private javax.swing.JButton BTNC6;
    private javax.swing.JButton BTNC7;
    private javax.swing.JButton BTNC8;
    private javax.swing.JButton BTNC9;
    private javax.swing.JButton C15;
    private javax.swing.JButton C16;
    private javax.swing.JButton C17;
    private javax.swing.JButton C18;
    private javax.swing.JButton C19;
    private javax.swing.JButton C20;
    private javax.swing.JButton C21;
    private javax.swing.JButton C22;
    private javax.swing.JButton C23;
    private javax.swing.JButton C24;
    private javax.swing.JButton C27;
    private javax.swing.JButton C28;
    private javax.swing.JButton C29;
    private javax.swing.JButton C30;
    private javax.swing.JButton C31;
    private javax.swing.JButton C32;
    private javax.swing.JButton C33;
    private javax.swing.JButton C34;
    private javax.swing.JButton C35;
    private javax.swing.JButton C36;
    private javax.swing.JComboBox<String> CBMULTIPLICADOR;
    private javax.swing.JComboBox<String> CBTOLERANCIA;
    private javax.swing.JTextField J1;
    private javax.swing.JTextField J2;
    private javax.swing.JTextField J3;
    private javax.swing.JTextField J4;
    private javax.swing.JTextField J5;
    private javax.swing.JTextField RES1;
    private javax.swing.JTextField RES2;
    private javax.swing.JTextField RES3;
    private javax.swing.JTextField RES4;
    private javax.swing.JTextField RES5;
    private javax.swing.JButton SALIR;
    private javax.swing.JLabel TOLERANCIA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
