/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ColoresResistencias;

import javax.swing.JOptionPane;

/**
 *
 * @author David Peñavasquez Va
 */
public class Ultimo extends javax.swing.JFrame {

    /**
     * Creates new form Ultimo
     */
    public Ultimo() {
        initComponents();
          this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fem = new javax.swing.JTextField();
        voltaje = new javax.swing.JTextField();
        resistencia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CBCONVER = new javax.swing.JComboBox<>();
        BTNCALCULAR = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FISICA ll");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("INTENSIDAD DE CORRIENTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("ELECTRICA  (I)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("fem( V )");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 50, 22));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("___");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 21, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("voltaje");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("________________________");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 170, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("resistencia ( Ω )");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));
        getContentPane().add(fem, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 40, -1));
        getContentPane().add(voltaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 40, -1));
        getContentPane().add(resistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 50, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("=");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 20, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("POTENCIA SUMINISTRADA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("=");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        txt1.setEditable(false);
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 80, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("=");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 20, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("POTENCIA DISIPADA");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        txt2.setEditable(false);
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 120, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("=");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 20, -1));

        txt3.setEditable(false);
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 120, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 255, 204));
        jLabel13.setText("A");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 20, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 255, 204));
        jLabel14.setText("W");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 255, 204));
        jLabel15.setText("W");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        CBCONVER.setBackground(new java.awt.Color(255, 255, 0));
        CBCONVER.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CBCONVER.setForeground(new java.awt.Color(255, 255, 255));
        CBCONVER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " CONVIERTE", " yotta", " zeta", " exa", " peta", " tera", " giga", " mega", " kilo", " hecto", " deca", " deci", " centi", " mili", " micro", " nano", " pico", " femto", " atto", " zepto", " yocto" }));
        CBCONVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCONVERActionPerformed(evt);
            }
        });
        getContentPane().add(CBCONVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 130, 60));

        BTNCALCULAR.setBackground(new java.awt.Color(0, 0, 255));
        BTNCALCULAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNCALCULAR.setForeground(new java.awt.Color(255, 255, 255));
        BTNCALCULAR.setText("CALCULAR");
        BTNCALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCALCULARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNCALCULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 120, 50));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LIMPIAR CAMPOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 150, 50));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, -1, 50));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESE DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 204, 0))); // NOI18N
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 550, 150));

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(51, 204, 0))); // NOI18N
        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 380, 110));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\David Peñavasquez Va\\Desktop\\imagenfisica.jpg")); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 300));

        jMenu1.setText("BY DAVID PEÑAVASQUEZ VASQUEZ");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCALCULARActionPerformed
      double fem1=Double.parseDouble(fem.getText());
      double voltaje1=Double.parseDouble(voltaje.getText());
      double resistencia1=Double.parseDouble(resistencia.getText());

      double r1;
      r1=(fem1-voltaje1)/resistencia1;
      
      String r3= Double.toString(r1);
      txt1.setText(r3);
      double r2;
      r2=r1*voltaje1;
      double r4;
      r4=Math.pow(r1, 2)*resistencia1;
      String R,R1;
      R=Double.toString(r2);
      R1=Double.toString(r4);
      txt2.setText(R);
      txt3.setText(R1);
       
      
      
    }//GEN-LAST:event_BTNCALCULARActionPerformed

    private void CBCONVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCONVERActionPerformed
      double fem1=Double.parseDouble(fem.getText());
      double voltaje1=Double.parseDouble(voltaje.getText());
      double resistencia1=Double.parseDouble(resistencia.getText());
      
      double r1;
     
      r1=(fem1-voltaje1)/resistencia1;
      
      String r3= Double.toString(r1);
      txt1.setText(r3);
      double r2;
      r2=r1*voltaje1;
      double r4;
      r4=Math.pow(r1, 2)*resistencia1;
      String R,R1;
      R=Double.toString(r2);
      R1=Double.toString(r4);
      txt2.setText(R);
      txt3.setText(R1);
        if(CBCONVER.getSelectedIndex()==1){
            double c2;
            c2=Math.pow(10, 24); 
            double c1;
            c1=r1/c2;
            double c3,c4;
            c3=r2/c2;
            c4=r4/c2;
            
            
            JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" YA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" YW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" YW");
      
            
        
    }
        if(CBCONVER.getSelectedIndex()==2){
            double c2;
            c2=Math.pow(10, 21); 
            double c1;
            c1=r1/c2;
            
       double c3,c4;
            c3=r2/c2;
            c4=r4/c2;
            
            
          JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" ZA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" ZW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" ZW");
        
        
    }
        if(CBCONVER.getSelectedIndex()==3){
            double c2;
            c2=Math.pow(10, 18); 
            double c1;
            c1=r1/c2;
            
      double c3,c4;
            c3=r2/c2;
            c4=r4/c2;
            
            
            JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" EA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" EW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" EW");
        
        
    }
        if(CBCONVER.getSelectedIndex()==4){
            double c2;
            c2=Math.pow(10, 15); 
            double c1;
            c1=r1/c2;
            
        double c3,c4;
            c3=r2/c2;
            c4=r4/c2;
            
            
         JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" PA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" PW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" PW");
        
        
    }
        if(CBCONVER.getSelectedIndex()==5){
            double c2;
            c2=Math.pow(10, 12); 
            double c1;
            c1=r1/c2;
            
          double c3,c4;
            c3=r2/c2;
            c4=r4/c2;
            
            
          JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" TA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" TW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" TW");
        
        
        
    }
        if(CBCONVER.getSelectedIndex()==6){
            double c2;
            c2=Math.pow(10, 9); 
            double c1;
            c1=r1/c2;
            
            double c3,c4;
            c3=r2/c2;
            c4=r4/c2;
            
            
       JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" GA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" GW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" GW");
        
        
        
    }
        if(CBCONVER.getSelectedIndex()==7){
            double c2;
            c2=Math.pow(10, 6); 
            double c1;
            c1=r1/c2;
            
              double c3,c4;
            c3=r2/c2;
            c4=r4/c2;
            
             JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" MA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" MW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" MW");
        
        
        
    }
        if(CBCONVER.getSelectedIndex()==8){
            double c2;
            c2=Math.pow(10, 3); 
            double c1;
            c1=r1/c2;
            
          double c3,c4;
            c3=r2/c2;
            c4=r4/c2;
            
            
          JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" kA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" kW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" kW");
        
        
        
    }
        if(CBCONVER.getSelectedIndex()==9){
            double c2;
            c2=Math.pow(10, 2); 
            double c1;
            c1=r1/c2;
            
            double c3,c4;
            c3=r2/c2;
            c4=r4/c2;
            
            
             JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" hA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" hW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" hW");
        
        
    }
        if(CBCONVER.getSelectedIndex()==10){
            double c2;
            c2=10; 
            double c1;
            c1=r1/c2;
            
             double c3,c4;
            c3=r2/c2;
            c4=r4/c2;
            
           JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" daA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" daW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" daW");
        
        
        
    }
        if(CBCONVER.getSelectedIndex()==11){
            double c2;
            c2=10; 
            double c1;
            c1=r1*c2;
             double c3,c4;
             c3=r2*c2;
             c4=r4*c2;
            
           JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" dA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" dW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" dW");
        
        
    }
        if(CBCONVER.getSelectedIndex()==12){
            double c2;
            c2=Math.pow(10, 2); 
            double c1;
            c1=r1*c2;
            
           double c3,c4;
             c3=r2*c2;
             c4=r4*c2;
            
           JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" cA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" cW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" cW");
        
        
    }
        if(CBCONVER.getSelectedIndex()==13){
            double c2;
            c2=Math.pow(10, 3); 
            double c1;
            c1=r1*c2;
            
   double c3,c4;
             c3=r2*c2;
             c4=r4*c2;
            
      JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" mA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" mW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" mW");
        
        
    }
        if(CBCONVER.getSelectedIndex()==14){
            double c2;
            c2=Math.pow(10, 6); 
            double c1;
            c1=r1*c2;
            
           double c3,c4;
             c3=r2*c2;
             c4=r4*c2;
            
        JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" uA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" uW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" uW");
        
        
    }
        if(CBCONVER.getSelectedIndex()==15){
            double c2;
            c2=Math.pow(10, 9); 
            double c1;
            c1=r1*c2;
            
             double c3,c4;
             c3=r2*c2;
             c4=r4*c2;
            
         JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" nA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" nW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" nW");
        
        
    }
        if(CBCONVER.getSelectedIndex()==16){
            double c2;
            c2=Math.pow(10, 12); 
            double c1;
            c1=r1*c2;
            
             double c3,c4;
             c3=r2*c2;
             c4=r4*c2;
            
         JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" pA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" pW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" pW");
        
        
    }
        if(CBCONVER.getSelectedIndex()==17){
            double c2;
            c2=Math.pow(10, 15); 
            double c1;
            c1=r1*c2;
            
           double c3,c4;
             c3=r2*c2;
             c4=r4*c2;
            
      JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" fA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" fW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" fW");
        
        
    }
        if(CBCONVER.getSelectedIndex()==18){
            double c2;
            c2=Math.pow(10, 18); 
            double c1;
            c1=r1*c2;
            
              double c3,c4;
             c3=r2*c2;
             c4=r4*c2;
            
          JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" aA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" aW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" aW");
        
        
    }
        if(CBCONVER.getSelectedIndex()==19){
            double c2;
            c2=Math.pow(10, 21); 
            double c1;
            c1=r1*c2;
            
           double c3,c4;
             c3=r2*c2;
             c4=r4*c2;
            
             JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" zA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" zW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" zW");
        
        
    }
        if(CBCONVER.getSelectedIndex()==20){
            double c2;
            c2=Math.pow(10, 24); 
            double c1;
            c1=r1*c2;
            
           double c3,c4;
             c3=r2*c2;
             c4=r4*c2;
            
       JOptionPane.showMessageDialog(null, "LA CONVERSION DE LA INTENSIDAD ES: " +  c1 +" yA"+"\nLA CONVERSION DE LA POTENCIA SUMINISTRADA ES: " +  c3 +" yW"+
                    "\nLA CONVERSION DE LA POTENCIA DISIPADA ES: " +  c4+" yW");
        
        
    }
        
        
    }//GEN-LAST:event_CBCONVERActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Ultimo n= new Ultimo();
      n.setVisible(false);
      dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       CBCONVER.setSelectedIndex(0);
        fem.setText("");
      voltaje.setText("");
      resistencia.setText("");
      txt1.setText("");
      txt2.setText("");
      txt3.setText("");
  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ultimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ultimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ultimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ultimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ultimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCALCULAR;
    private javax.swing.JComboBox<String> CBCONVER;
    private javax.swing.JTextField fem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField resistencia;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField voltaje;
    // End of variables declaration//GEN-END:variables
}
